### ISSUE TITLE
Add to OGA Theme Gallery

### ISSUE THREAD

**Issue by Jetup13** [TheBenny/RG351V-RetroBenny-PS5#1]
Beautiful theme! I would love to add it to the OGA Theme Gallery. I just need the theme folders corrected so it can be correctly downloaded from [Thememaster](https://github.com/JohnIrvine1433/ThemeMaster)'s Theme Gallery Mode. The themes content just needs to simply move up to the root of the git.

<details>
<summary>Current setup</summary>
<br>

RG351V-RetroBenny-PS5/_inc/

RG351V-RetroBenny-PS5/sounds/

RG351V-RetroBenny-PS5/videos/

RG351V-RetroBenny-PS5/back.wav

RG351V-RetroBenny-PS5/game_back.wav

RG351V-RetroBenny-PS5/game_launch.wav

RG351V-RetroBenny-PS5/game_scroll.wav

RG351V-RetroBenny-PS5/menu.wav

RG351V-RetroBenny-PS5/se_sys_click_game.wav

RG351V-RetroBenny-PS5/se_sys_cursor.wav

RG351V-RetroBenny-PS5/system_launch.wav

RG351V-RetroBenny-PS5/system_scroll.wav

RG351V-RetroBenny-PS5/systemscroll.wav

RG351V-RetroBenny-PS5/systemselect.wav

RG351V-RetroBenny-PS5/theme.xml
</details>

<details>
<summary>Correct setup</summary>
<br>

/_inc/

/sounds/

/videos/

back.wav

game_back.wav

game_launch.wav

game_scroll.wav

menu.wav

se_sys_click_game.wav

se_sys_cursor.wav

system_launch.wav

system_scroll.wav

systemscroll.wav

systemselect.wav

theme.xml
</details>

Nice work btw! I love the icons

**Comment by TheBenny** [comment]
Awesome thanks man!
I have a few more themes, a nesbox edit for the RG351V wood, a nesbox edit
for the RG351V black background, a PS2 one and Nes Mini Edit for the
RG351V.
I would love to add them as well, ill try and set them up using this file
structure
